### ISSUE TITLE
[New Rule] Common Nginx Error Messages.

### ISSUE THREAD

**Issue by fearfactor3** [prequel-dev/cre#10]
### Description

Brainstorming ideas for CRE rules that could be created for this tool to be utilized with very popular tools in the tech world.  First tool that has common errors in my mind is `nginx`.

### Related issues or PRs

N/A

### References

Insecure SSL/TLS Settings:
Using outdated SSL protocols or weak ciphers can make your website susceptible to attacks like SSL stripping or man-in-the-middle (MITM) attacks.

Solution:
Ensure that you’re using the latest TLS protocols (e.g., TLS 1.2 or 1.3) and strong ciphers. Regularly update your configurations to align with current best practices in SSL/TLS security.

**Comment by tonymeehan** [comment]
Thanks for starting the discussion on nginx issues, @fearfactor3.

This is an good opportunity to start pulling in some CREs for configuration files and configmaps.

```
$ k get configmaps -A -o json | jq -c | preq -d -r ./rule.yaml 
Parsing rules           done! [1 rules in 1ms; 1.27K rules/s]
Problems detected       done! [1 in 0s; 2.22K/s]
Reading stdin           done! [25.07KB in 0s; 115.55MB/s]
CRE-2025-0066        critical [1 hits @ 2025-04-23T15:37:44-05:00]
Matching lines          done! [1 lines in 0s; 4.52K lines/s]

Wrote report to preq-report-1745548560.json
```

One initial idea is adding something something for weak ciphers (RC4, DES-CBC3-SHA).

Something like this:

``` yaml
  rule:
    set:
      window: 1s
      event:
        source: cre.config.nginx
      match:
        - value: RC4-MD5
        - value: RC4-SHA
        - value: DES-CBC3-SHA
```
